import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "sonner";
import { SessionProvider } from 'next-auth/react'
import { auth } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()
  return (
    <SessionProvider session={session}>  
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased`}>
      <Toaster />
        {children}
      </body>
    </html>
    </SessionProvider>
  );
}
